-- Create notification service database tables

-- Create notification_templates table
CREATE TABLE notification_templates (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    subject_template VARCHAR(500),
    body_template TEXT NOT NULL,
    html_template TEXT,
    variables JSONB DEFAULT '{}',
    default_values JSONB DEFAULT '{}',
    validation_rules JSONB DEFAULT '{}',
    active BOOLEAN NOT NULL DEFAULT true,
    template_version INTEGER NOT NULL DEFAULT 1,
    parent_template_id BIGINT,
    sender_name VARCHAR(200),
    sender_email VARCHAR(200),
    reply_to VARCHAR(200),
    metadata JSONB DEFAULT '{}',
    tags VARCHAR(500),
    category VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255),
    
    CONSTRAINT fk_template_parent FOREIGN KEY (parent_template_id) REFERENCES notification_templates(id)
);

-- Create notifications table
CREATE TABLE notifications (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    subject VARCHAR(500),
    content TEXT,
    html_content TEXT,
    recipient_address VARCHAR(500) NOT NULL,
    sender_address VARCHAR(500),
    template_id BIGINT,
    template_variables JSONB DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    scheduled_at TIMESTAMP,
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    read_at TIMESTAMP,
    expires_at TIMESTAMP,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retry_attempts INTEGER NOT NULL DEFAULT 3,
    next_retry_at TIMESTAMP,
    error_message TEXT,
    external_id VARCHAR(255),
    correlation_id VARCHAR(255),
    reference_type VARCHAR(50),
    reference_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255),
    
    CONSTRAINT fk_notification_template FOREIGN KEY (template_id) REFERENCES notification_templates(id)
);

-- Create notification_deliveries table
CREATE TABLE notification_deliveries (
    id BIGSERIAL PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    channel VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    recipient_address VARCHAR(500) NOT NULL,
    sender_address VARCHAR(500),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    attempted_at TIMESTAMP,
    delivered_at TIMESTAMP,
    failed_at TIMESTAMP,
    next_attempt_at TIMESTAMP,
    response_code VARCHAR(50),
    response_message TEXT,
    error_message TEXT,
    external_id VARCHAR(255),
    external_status VARCHAR(100),
    provider_name VARCHAR(100),
    provider_message_id VARCHAR(255),
    provider_response JSONB DEFAULT '{}',
    delivery_metadata JSONB DEFAULT '{}',
    processing_time_ms BIGINT,
    cost_cents INTEGER,
    opened_at TIMESTAMP,
    clicked_at TIMESTAMP,
    bounced_at TIMESTAMP,
    bounce_reason VARCHAR(500),
    unsubscribed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255),
    
    CONSTRAINT fk_delivery_notification FOREIGN KEY (notification_id) REFERENCES notifications(id)
);

-- Create notification_preferences table
CREATE TABLE notification_preferences (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    channel VARCHAR(20) NOT NULL,
    type VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    quiet_hours_enabled BOOLEAN NOT NULL DEFAULT false,
    quiet_hours_start TIME,
    quiet_hours_end TIME,
    timezone VARCHAR(50) DEFAULT 'UTC',
    language VARCHAR(10) DEFAULT 'en',
    frequency_limit_per_hour INTEGER,
    frequency_limit_per_day INTEGER,
    minimum_priority VARCHAR(20),
    channel_settings JSONB DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    opt_out_reason VARCHAR(500),
    global_opt_out BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(255)
);
